on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
name: Specification version check
jobs:
  # Get the latest TUF specification release and open an issue (if needed)
  specification-bump-check:
    permissions:
      contents: read
      issues: write
    uses: theupdateframework/specification/.github/workflows/check-latest-spec-version.yml@master
    with:
      tuf-version: "v1.0.20" # Should be updated to the version the project supports either manually or extracted automatically. You can see how python-tuf did that as an example.
